version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
  elasticsearchdb:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.5.4"
    container_name: elasticsearchdb
    environment:
      - "cluster.name=my-cluster"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    expose:
      - "9200"
